from flask import Blueprint, jsonify
import os
import json
import sys

# 1. Add project root to path so we can import 'src'
# Logic: routes.py is in dashboard/backend/api/ -> ../../../ reaches root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../')))
from src.data_loader import load_oil_data, load_events_data

api_bp = Blueprint('api', __name__)

@api_bp.route('/prices')
def get_prices():
    """Returns historical price data from 2014 onwards."""
    try:
        df = load_oil_data()
        # Filter for the last ~10 years to keep the dashboard responsive
        df = df[df['Date'].dt.year >= 2014]
        
        # Convert dates to string format for JSON compatibility
        # assign() is a clean way to update the column without SettingWithCopy warnings
        data = df.assign(Date=df['Date'].dt.strftime('%Y-%m-%d')).to_dict(orient='records')
        return jsonify(data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@api_bp.route('/events')
def get_events():
    """Returns the curated geopolitical events data."""
    try:
        events = load_events_data()
        # Ensure events date column is string for JSON
        if 'Date' in events.columns:
             events['Date'] = events['Date'].astype(str)
        return jsonify(events.to_dict(orient='records'))
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@api_bp.route('/analysis')
def get_analysis_results():
    """Loads results generated by the PyMC model in Task 2."""
    # Logic: Look for data inside dashboard/backend/data/
    backend_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    results_path = os.path.join(backend_root, 'data', 'analysis_results.json')
    
    try:
        with open(results_path, 'r') as f:
            data = json.load(f)
        return jsonify(data)
    except FileNotFoundError:
        # Return empty list if analysis hasn't been run yet so frontend doesn't crash
        return jsonify([])
    except Exception as e:
        return jsonify({"error": str(e)}), 500